version: "3.3"
services:
  spark-master:
    image: cluster-apache-spark:3.4.0
    hostname: "spark-master"
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./events:/tmp/spark-events
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: cluster-apache-spark:3.4.0
    hostname: "spark-worker-a"
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./events/spark:/tmp/spark-events
  spark-worker-b:
    image: cluster-apache-spark:3.4.0
    hostname: "spark-worker-b"
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
        - ./events/spark:/tmp/spark-events
  spark-history:
    image: cluster-apache-spark:3.4.0
    hostname: "spark-history"
    ports:
      - "19090:18080"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./events/spark:/tmp/spark-events
    environment:
      - SPARK_LOCAL_IP=spark-history
      - SPARK_WORKLOAD=history
  demo-database:
    image: postgres:15
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=casa1234
  otelcol:
    image: otelcol:1.0.0
    platform: "linux/amd64"
    volumes:
       - ./OT/config.yaml:/tmp/config.yaml
       - ./events/ot:/tmp/ot
    depends_on:
       - spark-master
       - spark-worker-a
       - spark-worker-b
       - spark-history


