# ./bin/otelcontribcol_darwin_arm64 --config ./receiver/apachesparkreceiver/testdata/config.yaml
receivers:
  apachespark:
    collection_interval: 15s
    endpoint: http://spark-history:18080
exporters:
  file:
    path: /tmp/ot/metrics.json

service:
  pipelines:
    metrics:
      receivers: [apachespark]
      exporters: [file]
